apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-back-deployment
  labels:
    app: opsdesk-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opsdesk-backend
  template:
    metadata:
      labels:
        app: opsdesk-backend
    spec:
      containers:
      - name: opsdesk-backend
        image: avi03/051026backend:v1
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: DB_NAME
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: JWT_SECRET
        - name: MONGODB
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: MONGODB
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi        