apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-front-deployment
  labels:
    app: opsdesk-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opsdesk-frontend
  template:
    metadata:
      labels:
        app: opsdesk-frontend
    spec:
      containers:
      - name: opsdesk-frontend
        image: avi03/frontend:latest
        ports:
        - containerPort: 8080