apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: back-app
  namespace: argocd
spec:
  project: OpsDesk
  source:
    repoURL: https://github.com/AvinashShetty7/END-to-END-kubernetes-Deployement-Using-ArgoCD-and-Terraform
    targetRevision: main
    path: backend/Helm/back-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true